#!/usr/bin/env bash
# Quick Setup Guide for AI Asset Generation

echo "🎬 Tidum AI Asset Generation Quickstart"
echo ""
echo "================================"
echo "STEP 1: Generate Illustrations"
echo "================================"
echo ""
echo "Option A: Using Replicate API (EASIEST)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Sign up: https://replicate.com"
echo "2. Get API token from: https://replicate.com/account"
echo "3. Set environment:"
echo "   export REPLICATE_API_TOKEN=\"your-token\""
echo ""
echo "4. Generate images:"
echo ""
echo "   # Image 1: Morning Routine"
echo "   replicate predict stability-ai/stable-diffusion \\"
echo "     -i prompt=\"Professional person starting their day with Tidum app, coffee cup, morning sunlight, modern flat design, teal and green colors\""
echo ""
echo "   # Image 2: Data Analytics"
echo "   replicate predict stability-ai/stable-diffusion \\"
echo "     -i prompt=\"Charts and graphs coming to life, productivity trends, data visualization, modern style, teal and green gradient\""
echo ""
echo "   # Image 3: Collaboration"
echo "   replicate predict stability-ai/stable-diffusion \\"
echo "     -i prompt=\"Team members collaborating and sharing knowledge, diverse team, positive energy, professional, modern design\""
echo ""
echo "5. Save output images to:"
echo "   ✓ client/public/illustrations/morning-routine.png"
echo "   ✓ client/public/illustrations/data-analytics.png"
echo "   ✓ client/public/illustrations/collaboration.png"
echo ""
echo ""
echo "Option B: Using Midjourney"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Sign up: https://midjourney.com"
echo "2. Use Discord bot with prompts above"
echo "3. Right-click image → Open in browser"
echo "4. Download and save to illustrations/ folder"
echo ""
echo ""
echo "Option C: Using Google Vertex AI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Create Google Cloud project"
echo "2. Enable: Vertex AI API"
echo "3. See: AI_GENERATION_GUIDE.md for detailed setup"
echo ""
echo ""
echo "================================"
echo "STEP 2: Create Videos"
echo "================================"
echo ""
echo "Option A: Using Runway ML (BEST)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Sign up: https://runwayml.com"
echo "2. Create project → Gen-2 model"
echo "3. Upload illustration image"
echo "4. Add prompt:"
echo ""
echo "   Video 1: 'Smooth camera pan showing time-tracking interface'"
echo "   Video 2: 'Charts animating, data flowing, bars growing'"
echo "   Video 3: 'Team members appearing, documents sharing, collaboration'"
echo ""
echo "5. Export as MP4"
echo "6. Save to: client/public/videos/"
echo ""
echo ""
echo "Option B: Using D-ID (For Talking)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Sign up: https://www.d-id.com"
echo "2. Create animated avatar"
echo "3. Upload illustration + script"
echo "4. Export video"
echo ""
echo ""
echo "Option C: Simple MP4 Creation (DIY)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Using FFmpeg + screenshot transitions:"
echo ""
echo "  ffmpeg -framerate 1/3 -i client/public/screenshots/time-tracking.png -c:v libx264 -pix_fmt yuv420p client/public/videos/time-tracking-tutorial.mp4"
echo ""
echo ""
echo "================================"
echo "STEP 3: Verify & Integrate"
echo "================================"
echo ""
echo "Run this after adding assets:"
echo ""
echo "  node scripts/integrate-assets.mjs"
echo ""
echo "This will:"
echo "  ✓ Check all assets are present"
echo "  ✓ Show file sizes"
echo "  ✓ Generate integration code"
echo ""
echo ""
echo "================================"
echo "STRUCTURE"
echo "================================"
echo ""
echo "client/public/"
echo "├── screenshots/          (✓ Already created)"
echo "│   ├── landing.webp"
echo "│   ├── time-tracking.webp"
echo "│   ├── reports-dashboard.webp"
echo "│   ├── case-management.webp"
echo "│   └── admin-panel.webp"
echo "│"
echo "├── illustrations/        (TO GENERATE)"
echo "│   ├── morning-routine.png"
echo "│   ├── data-analytics.png"
echo "│   └── collaboration.png"
echo "│"
echo "└── videos/              (TO GENERATE)"
echo "    ├── time-tracking-tutorial.mp4"
echo "    ├── reports-generation.mp4"
echo "    └── case-management-flow.mp4"
echo ""
echo ""
echo "================================"
echo "TIMELINE"
echo "================================"
echo ""
echo "  ⏱️  Illustrations: 5-15 minutes"
echo "  ⏱️  Videos: 15-30 minutes per video"
echo "  ⏱️  Integration: 5 minutes"
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📊 TOTAL: ~1-2 hours"
echo ""
echo ""
echo "Need help? See:"
echo "  📖 AI_GENERATION_GUIDE.md"
echo "  🔗 https://replicate.com/docs"
echo "  🔗 https://docs.runwayml.com"
echo ""
